const UserActionTypes = {
    SET_CURRENT_USER : 'SET_CURRENT_USER',
    SING_IN_SUCCESS : 'SING_IN_SUCCESS',
    SING_IN_FAILURE : 'SING_IN_FAILURE',
    CHECK_USER_SESSION : 'CHECK_USER_SESSION',
    SIGN_OUT_SUCCESS : 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
    SIGN_UP_START : 'SIGN_UP_START',
    SIGN_UP_SUCCESS : 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE : 'SIGN_UP_FAILURE'
}

export default UserActionTypes;